export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRIES_BY_QUERY = "FETCH_COUNTRIES_BY_QUERY";
export const FETCH_COUNTRIES_BY_REGION = "FETCH_COUNTRIES_BY_REGION";
export const UPDATE_REGION = "UPDATE_REGION";
export const UPDATE_QUERY = "UPDATE_QUERY";
